name: audio_music_player
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  just_audio: ^0.9.36
  audio_video_progress_bar: ^2.0.1
  rxdart: ^0.27.7
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  sliding_sheet: ^0.5.2
  sliding_sheet2: ^2.0.1
  just_audio_background: ^0.0.1-beta.11

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

